Street + Cross Street update
Stuyk/altv-athena pull request #180
Opened 2022-04-29 10:24 UTC by Locutus1119

2022-04-29 12:16 UTC, Stuyk requested changes

2022-04-29 12:16 UTC, Stuyk commented on src/core/plugins/core-hud/webview/Hud.vue
> +.location-placement {
Unfortunately this is not going to be positioned correctly for very wide screens. We'll need calculations from the client-side to the WebView to determine the exact position of the radar based on what screen resolution they are running.

Example of a minimap on a wider screen setup:
![](https://i.imgur.com/E7m1bsH.png)

2022-04-30 16:33 UTC, leonardssh requested changes

2022-04-30 16:33 UTC, leonardssh commented on src/core/plugins/core-hud/client/index.ts
> +    static defaultCrossStreetComponent(propName: string) {
Let's keep consistency about the spaces between class methods.

```suggestion
    }

    static defaultStreetComponent(propName: string) {
        const pos = alt.Player.local.pos;
        const streetHash = native.getStreetNameAtCoord(pos.x, pos.y, pos.z, null, null,)[1];
        const value = native.getStreetNameFromHashKey(streetHash)
        InternalFunctions.passComponentInfo(propName, value);
    }
    
    static defaultCrossStreetComponent(propName: string) {
```

2022-05-13 11:56 UTC, closed without merging