add Weapon Damage and Deformation multipliers to IVehicleHandling
Stuyk/altv-athena pull request #227
Opened 2022-06-06 04:30 UTC by dexslab

Needs for proper damage calculations for weapons and vehicle degradation.

2022-06-06 16:14 UTC, dexslab commented
I added more to my PR please review again thanks 😄

2022-06-06 16:52 UTC, dexslab commented on src/core/server/extensions/vehicleFuncs.ts
> +            vehicle.setHealthDataBase64(vehicle.data.damage);
I am in the process of revising this please wait for next commit 😄

2022-06-07 11:25 UTC, Derison requested changes

2022-06-07 11:25 UTC, Derison commented on src/core/server/extensions/vehicleFuncs.ts
> +    }
```suggestion
            }
        };
    }
```

2022-06-07 22:47 UTC, dexslab commented on src/core/server/extensions/vehicleFuncs.ts
> +        let damageObject = {
Ya prolly

2022-06-10 16:28 UTC, merged