[Root]: Added default color for factions + added two new types.
Stuyk/altv-athena pull request #294
Opened 2022-09-24 16:18 UTC by Kuroosh

This will add a default color for factions + the new types `medic` & `mechanic`.
The color PR will be needed for the color palette in the /fopen window ( in the next FR ) ( for faction chat color, gangwar, etc etc. )

2022-09-24 17:05 UTC, Progefix commented
medic is a state faction. i guess stuykt dont wont specific factions stuff like lspd lsmd etc.

2022-09-24 17:20 UTC, Kuroosh commented
> medic is a state faction. i guess stuykt dont wont specific factions stuff like lspd lsmd etc.

Well... yes & no.
medics should not be able to arrest people.
lspd should not be able to revive other people xd

2022-09-24 17:21 UTC, Kuroosh commented
checking it in a non-dynamic way ( by id ) isn't very nice.. 
so if a faction has a type ( like state ( LSPD, FBI, Army ) factions ) 
its easier to interact with that.

2022-09-26 12:50 UTC, Stuyk commented
I think this could be implemented in a way that would allow the expansion of faction types without touching it directly or adding opinionated types to it like; oh we need EMT cause that's what our gamemode needs.

ie. Change `type` to
```
type: "x" | "y" | "z";
```

Can probably pass a template type to the Faction interface itself.

Below is just mock code of what I'm thinking.
```ts
interface <T>Faction {
    ...
    type: "x" | "y" | "z" & T?
}
```

2022-09-26 12:53 UTC, Stuyk requested changes

2022-09-26 12:53 UTC, Stuyk commented on src/core/plugins/core-factions/shared/interfaces.ts
> +    color: Color;
Use `alt.RGBA`

2022-09-26 12:53 UTC, Stuyk commented on src/core/plugins/core-factions/shared/interfaces.ts
>      type: string;
Use a Template Type that can be passed to the Faction interface with a default of the `FactionTypes`.

2022-09-26 13:33 UTC, Kuroosh commented on src/core/plugins/core-factions/shared/interfaces.ts
> +    color: Color;
Sure, new PR will coming soon :)

2022-10-02 13:30 UTC, closed without merging