Refueling: Specify fuel amount
Stuyk/altv-athena pull request #311
Opened 2022-10-01 14:52 UTC by ItsSpencer

I added the option to specify the fuel amount to the fueling dialog at gas stations. Doing this I also touched the Job-Dialog and added an optional slider, because the fueling-dialog uses this Job-Dialog to initiate the refueling process. 

But I think a slider could also be useful in the job dialog, e.g. specify the amount of pizzas to deliver and so on. So I edited the Job-Dialog instead of creating a whole new dialog. Hope that is okay :)

2022-10-01 21:39 UTC, Stuyk requested changes

2022-10-01 21:39 UTC, Stuyk commented on src-webviews/src/pages/job/Job.vue
> +            <div class="split split-full center pt-4" v-if="maxAmount !== undefined">
This actually shouldn't be in job trigger at all. This probably needs to be its own new Vue file. To prevent conflicts with other job triggers.

2022-10-01 21:39 UTC, Stuyk commented on src/core/client/views/job.ts
> +    static accept(amount?: number) {
Shouldn't be in job trigger; needs to be own vue file.

2022-10-01 21:39 UTC, Stuyk commented on src/core/shared/interfaces/jobTrigger.ts
> +    maxAmount?: number;
Shouldn't be in job trigger.

2022-10-03 13:00 UTC, ItsSpencer commented
I moved the code now into extra fuel-components

2022-10-04 14:48 UTC, merged